name: train_val_test_split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=24.3.1
  - requests=2.32.5
  - scikit-learn=1.7.2
  - pip:
      - mlflow==3.4.0
      - wandb==0.16.3
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
