name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<2.0
  - pyyaml
  - pip=24.3.1
  - pip:
      - mlflow==3.4.0
      - wandb==0.16.3
      - hydra-core==1.3.2
